channels:
- conda-forge
- defaults

dependencies:
- python=3.10
- pydantic=1.10.0
- intake-esm=2023.6.14
- s3fs
- jupyterlab
- matplotlib
- xarray
- pandas
- scikit-learn
- tqdm
- flaml
- fastparquet
- pip
- pip:
  - netCDF4==1.5.8
  - haversine
name: aws_urban